[meta]
name     = "Extra Leaderboard Positions"
author   = "Banalian"
category = "Race"
version  = "1.4"
siteid = 169


[script]
dependencies = [ "NadeoServices" ]
imports = [ "Time.as", "Permissions.as"]