[meta]
name     = "Extra Leaderboard Positions"
author   = "Banalian"
category = "Race"
version  = "1.2"
siteid = 169

perms = "paid"

[script]
dependencies = [ "NadeoServices" ]
imports = [ "Icons.as", "Time.as", "Permissions.as"]