[meta]
name     = "Extra Leaderboard Positions"
author   = "Banalian"
category = "Race"
version  = "1.5"
siteid = 169


[script]
dependencies = [ "NadeoServices", "VehicleState" ]
imports = [ "Time.as", "Permissions.as"]