[meta]
name     = "Extra Leaderboard Positions"
author   = "Banalian"
category = "Race"
version  = "1.0"

perms = "paid"

[script]
dependencies = [ "NadeoServices" ]
imports = [ "Icons.as", "Time.as"]