[meta]
name     = "Extra Leaderboard Positions"
author   = "Banalian"
category = "Race"
version  = "2.0.1"
siteid = 169


[script]
dependencies = [ "NadeoServices", "VehicleState" ]
optional_dependencies = [ "ChampionMedals" ]