[meta]
name     = "Extra Leaderboard Positions"
author   = "Banalian"
category = "Race"
version  = "2.6.5"
siteid = 169


[script]
dependencies = [ "NadeoServices", "VehicleState" ]
optional_dependencies = [ "ChampionMedals", "SBVilleCampaignChallenges", "WarriorMedals", "s314keMedals", "UltimateMedalsExtended"]